# Generated by Django 3.0.7 on 2020-06-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='name',
            new_name='sentence',
        ),
    ]
