# Generated by Django 3.0.7 on 2020-06-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200603_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='body',
        ),
    ]
